runtime: java17
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  max_concurrent_requests: 50
  target_throughput_utilization: 0.75
  max_pending_latency: 30ms
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
entrypoint: java -XX:+UseStringDeduplication -jar SOCIALMEDIA2-0.0.1-SNAPSHOT.jar
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
handlers:
- url: /_ah/health
  script: auto
  secure: always
